name: modules_template
description: >
  Highly scalable Flutter starter kit, designed with an optimal predefined structure 
  and inclusive of libraries that are widely applicable in numerous use cases.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependency_overrides:
  meta: ^1.15.0
  js: ^0.7.1

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # BLoC
  bloc_concurrency: ^0.2.5
  bloc_event_transformers: ^1.0.1
  flutter_bloc: ^8.1.5

  # Networking
  dio: ^5.4.3

  # Persisting
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  # Logging
  talker: ^4.2.3
  talker_dio_logger: ^4.2.3
  talker_bloc_logger: ^4.2.3
  talker_riverpod_logger: ^1.0.3

  # Utils
  collection: ^1.18.0
  equatable: ^2.0.5
  get_it: ^7.7.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  provider: ^6.1.2
  intl: ^0.19.0
  share_plus: ^9.0.0
  stack_trace: ^1.11.1
  validators: ^3.0.0
  back_button_interceptor: ^7.0.3
  url_launcher: ^6.3.0

  # UI
  gap: ^3.0.1
  group_button: ^5.3.4
  flutter_easyloading: ^3.0.5
  auto_size_text: ^3.0.0
  fluttertoast: ^8.2.6
  ispect: ^1.1.8

  # Authentication
  flutter_login_facebook: ^2.0.0
  google_sign_in: ^6.2.1
  local_auth: ^2.2.0
  sign_in_with_apple: ^6.1.0
  smart_auth: ^2.0.0

  # Other
  cached_network_image: ^3.3.1
  flutter_inappwebview: ^6.0.0
  flutter_multi_formatter: ^2.12.8
  flutter_svg: ^2.0.10
  loader_overlay: ^4.0.0
  shimmer: ^3.0.0
  envied: ^0.5.4+1
  go_router: ^14.1.4

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  # Lints
  # sizzle_lints: ^2.0.2
  # custom_lint: ^0.6.4
  flutter_lints: ^4.0.0 

    # Utils
  flutter_gen_runner: ^5.5.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

  # Codegen
  build_runner: ^2.4.10
  envied_generator: ^0.5.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/shared/fonts/
    - assets/shared/icons/
    - assets/shared/images/
    - assets/one/images/
    - assets/one/icons/
    - assets/two/images/
    - assets/two/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/shared/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/shared/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/shared/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/shared/fonts/inter/Inter-Bold.ttf
          weight: 700
    - family: Montserrat Alternates
      fonts:
        - asset: assets/shared/fonts/montserrat_alternates/MontserratAlternates-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/_shared/
  line_length: 120
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
  main_locale: ru
  arb_dir: lib/_shared/arb
  output_dir: lib/core/l10n/generated

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/shared/images/icon.png"
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/shared/images/logo_native_splash.png
  ios: false
  web: false
  android_12:
    color: "#FFFFFF"
    image: assets/shared/images/logo_native_splash.png
